/*
 * BiblioHouse - Un gestor de biblioteca personal.
 * Copyright (C) 2025 ferlagod
 *
 * Este programa es software libre: usted puede redistribuirlo y/o modificarlo
 * bajo los términos de la Licencia Pública General de GNU tal como se publica
 * por la Free Software Foundation, ya sea la versión 3 de la Licencia, o
 * (a su opción) cualquier versión posterior.
 *
 * Este programa se distribuye con la esperanza de que sea útil, pero
 * SIN NINGUNA GARANTÍA; sin siquiera la garantía implícita de
 * COMERCIABILIDAD o APTITUD PARA UN PROPÓSITO PARTICULAR. Vea la
 * Licencia Pública General de GNU para más detalles.
 *
 * Usted debería haber recibido una copia de la Licencia Pública General de GNU
 * junto con este programa. Si no es así, vea <https://www.gnu.org/licenses/>.
 */
package com.bibliohouse.ui;

/**
 * JDialog que muestra una lista de los libros duplicados encontrados en la
 * aplicación BiblioHouse.
 *
 * @author ferlagod
 */
public class VentanaDuplicados extends javax.swing.JDialog {

    /**
     * Crea una nueva instancia de VentanaDuplicados.
     *
     * @param parent El JFrame padre desde el cual se lanza este diálogo.
     * @param modal Indica si el diálogo debe ser modal.
     * @param textoDuplicados El texto que contiene la lista de libros
     * duplicados.
     */
    public VentanaDuplicados(java.awt.Frame parent, boolean modal, String textoDuplicados) {
        super(parent, modal);
        initComponents();

        setResizable(false);

        setTitle("Busqueda de duplicados - BiblioHouse");

        // Asigna el texto y asegura que el scroll se muestre desde el principio
        txtAreaDuplicados.setText(textoDuplicados);
        txtAreaDuplicados.setCaretPosition(0);

        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDuplicados = new javax.swing.JTextArea();
        btnClosedDuplicados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Se encontraron los siguientes posibles duplicados:");

        txtAreaDuplicados.setEditable(false);
        txtAreaDuplicados.setColumns(20);
        txtAreaDuplicados.setRows(5);
        jScrollPane1.setViewportView(txtAreaDuplicados);

        btnClosedDuplicados.setText("Cerrar");
        btnClosedDuplicados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClosedDuplicadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 506, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClosedDuplicados)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnClosedDuplicados)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cierra el diálogo cuando se hace clic en el botón "Cerrar".
     *
     * @param evt El evento de acción que desencadena este método.
     */

    private void btnClosedDuplicadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClosedDuplicadosActionPerformed
        dispose();
    }//GEN-LAST:event_btnClosedDuplicadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClosedDuplicados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaDuplicados;
    // End of variables declaration//GEN-END:variables
}
