/*
 * BiblioHouse - Un gestor de biblioteca personal.
 * Copyright (C) 2025 ferlagod
 *
 * Este programa es software libre: usted puede redistribuirlo y/o modificarlo
 * bajo los términos de la Licencia Pública General de GNU tal como se publica
 * por la Free Software Foundation, ya sea la versión 3 de la Licencia, o
 * (a su opción) cualquier versión posterior.
 *
 * Este programa se distribuye con la esperanza de que sea útil, pero
 * SIN NINGUNA GARANTÍA; sin siquiera la garantía implícita de
 * COMERCIABILIDAD o APTITUD PARA UN PROPÓSITO PARTICULAR. Vea la
 * Licencia Pública General de GNU para más detalles.
 *
 * Usted debería haber recibido una copia de la Licencia Pública General de GNU
 * junto con este programa. Si no es así, vea <https://www.gnu.org/licenses/>.
 */
package com.bibliohouse.ui;

import java.io.File;
import javax.swing.JFileChooser;

/**
 * JDialog para que el usuario configure las preferencias de la aplicación
 * BiblioHouse.
 *
 * @author ferlagod
 */
public class VentanaConfiguracion extends javax.swing.JDialog {

    private String rutaSeleccionada;
    private String temaSeleccionado;
    private boolean guardado = false;

    /**
     * Crea una nueva instancia de VentanaConfiguracion.
     *
     * @param parent El JFrame padre desde el cual se lanza este diálogo.
     * @param modal Indica si el diálogo debe ser modal.
     * @param rutaActual La ruta actual de exportación que se mostrará en el
     * diálogo.
     */
    public VentanaConfiguracion(java.awt.Frame parent, boolean modal, String rutaActual, String temaActual) {
        super(parent, modal);
        initComponents();
        this.rutaSeleccionada = rutaActual;
        txtRutaExportacion.setText(rutaActual); // Muestra la ruta actual
        this.temaSeleccionado = temaActual;

        // Seleccionar el tema actual en el ComboBox
        if (temaActual != null && temaActual.contains("Dark")) {
            cmbTema.setSelectedIndex(1);
        } else {
            cmbTema.setSelectedIndex(0);
        }

        setTitle("Configuración - BiblioHouse");
        setResizable(false);
        setLocationRelativeTo(parent);
    }

    /**
     * Devuelve la ruta seleccionada por el usuario.
     *
     * @return La ruta como String, o null si el usuario canceló.
     */
    public String getRutaSeleccionada() {
        return rutaSeleccionada;
    }

    /**
     * Devuelve el tema seleccionada por el usuario.
     *
     * @return El tema seleccionado.
     */
    public String getTemaSeleccionado() {
        return guardado ? temaSeleccionado : null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtRutaExportacion = new javax.swing.JTextField();
        lblDescripcionRuta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTema = new javax.swing.JLabel();
        cmbTema = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setText("Configuración");

        btnCambiar.setText("Cambiar...");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtRutaExportacion.setEditable(false);

        lblDescripcionRuta.setText("Carpeta por defecto para exportar:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cambio de tema"));

        lblTema.setText("Tema Claro / Oscuro");

        cmbTema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tema Claro (Estilo Mac)", "Tema Oscuro (Estilo Mac)" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTema)
                .addGap(59, 59, 59)
                .addComponent(cmbTema, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTema)
                    .addComponent(cmbTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar))
                            .addComponent(txtRutaExportacion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCambiar)
                                    .addComponent(lblDescripcionRuta)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(lblTitulo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcionRuta)
                .addGap(18, 18, 18)
                .addComponent(txtRutaExportacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCambiar)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre un diálogo para seleccionar una nueva carpeta de exportación.
     *
     * @param evt El evento de acción que desencadena este método.
     */
    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Seleccionar carpeta de exportación por defecto");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (txtRutaExportacion.getText() != null && !txtRutaExportacion.getText().isEmpty()) {
            chooser.setCurrentDirectory(new File(txtRutaExportacion.getText()));
        }

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            txtRutaExportacion.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnCambiarActionPerformed

    /**
     * Guarda la ruta seleccionada y cierra el diálogo.
     *
     * @param evt El evento de acción que desencadena este método.
     */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        this.rutaSeleccionada = txtRutaExportacion.getText();
        //Guardamos el nombre de la clase del tema, no el texto descriptivo
        if (cmbTema.getSelectedIndex() == 1) {
            this.temaSeleccionado = "com.formdev.flatlaf.themes.FlatMacDarkLaf";
        } else {
            this.temaSeleccionado = "com.formdev.flatlaf.themes.FlatMacLightLaf";
        }
        this.guardado = true;
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * Cierra el diálogo sin guardar cambios.
     *
     * @param evt El evento de acción que desencadena este método.
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.rutaSeleccionada = null;
        this.guardado = false; //
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbTema;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescripcionRuta;
    private javax.swing.JLabel lblTema;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtRutaExportacion;
    // End of variables declaration//GEN-END:variables
}
